name: Compile LLink ARM Linux and UV
on: workflow_dispatch
jobs:
  FunctionCompile-GNULinux-ARM:
    runs-on: macos-latest
    env:
      WOLFRAM_SYSTEM_ID: Linux-ARM
      WOLFRAMENGINE_CACHE_KEY: WolframEngine-BA
      WOLFRAMENGINE_INSTALLATION_DIRECTORY: "/Applications/Wolfram Engine.app"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install WE
        run: |
            set -eux -o pipefail
            chmod +x ./.github/workflows/install_arm.sh
            WE_MODE=install bash ./.github/workflows/install_arm.sh
            sudo apt install libuv1-dev -y

      - name: Compile function
        env:
          WOLFRAMENGINE_EXECUTABLES_DIRECTORY: "${{ env.WOLFRAMENGINE_INSTALLATION_DIRECTORY }}/Contents/Resources/Wolfram Player.app/Contents/MacOS"
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
          WOLFRAMSCRIPT_KERNELPATH: "${{ env.WOLFRAMENGINE_INSTALLATION_DIRECTORY }}/Contents/MacOS/WolframKernel"
        run: |
          export PATH="${{ env.WOLFRAMENGINE_EXECUTABLES_DIRECTORY }}:$PATH"

          wolframscript -debug -verbose -script ./compile_uv_arm.wls

      - name: Archive compiled libraries
        uses: actions/upload-artifact@v4
        with:
          name: CompiledFunctionLibraries-${{ env.WOLFRAM_SYSTEM_ID }}
          path: |
            LibraryResources/
          if-no-files-found: error

