name: Wolfram Engine GnuLINUX ARM Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04-arm # Use an ARM64 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: steps
        run: |
            set -eux -o pipefail
            chmod +x ./.github/workflows/install_arm.sh
            WE_MODE=install bash ./.github/workflows/install_arm.sh
            sudo apt install libuv1-dev -y

            
